CREATE TABLE IF NOT EXISTS probable_exercise_sources (
  id SERIAL PRIMARY KEY,
  subject TEXT NOT NULL,
  topic TEXT NOT NULL,
  file_name TEXT NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT probable_exercise_sources_unique UNIQUE (subject, topic, file_name)
);

CREATE INDEX IF NOT EXISTS probable_exercise_sources_subject_topic_idx
  ON probable_exercise_sources(subject, topic);

INSERT INTO probable_exercise_sources (subject, topic, file_name) VALUES
  ('Physique', 'Revision generale', 'Fhysique_Philo_2022_Philo-C-D.pdf'),
  ('Physique', 'Revision generale', 'Physique-2025.pdf'),
  ('Physique', 'Revision generale', 'physique-2021-Bac-Permanent-.pdf'),
  ('Physique', 'Revision generale', 'Physiques-NS4-2014-2016-2018.pdf'),
  ('Physique', 'Modele d examen', 'Physique-modele-examen (1).pdf'),
  ('Physique', 'Mecanique', 'Physique-NS4-mecanique-decembre-2025.pdf'),
  ('Physique', 'Entropie', 'Physique-NS4-SMP-SVT-Entropie.pdf'),
  ('Physique', 'Vitesse', 'Physique-SMP-SVT-Vitesse.pdf'),
  ('Physique', 'Vitesse', 'Physique_2022_SVT-SMP_Vitesse.pdf'),
  ('Physique', 'Photon', 'Physique_2015_SVT-SMP_Photon.pdf'),
  ('Physique', 'Phytophage', 'Physique_2016_SVT-SMP_Phytophage.pdf'),
  ('Physique', 'Phytotron', 'Physique_2016_SVT-SMP_Phytotron.pdf'),
  ('Physique', 'Dipole electrique', 'Physique_2018_SVT-SMP_Dipole.pdf'),
  ('Physique', 'Cinetique', 'Physique_2019_SES_Cinetique.pdf'),
  ('Physique', 'Impedance', 'Physique_2019_SES_Impedance.pdf'),
  ('Physique', 'Aimantation', 'Physique_2019_SVT-SMP_Aimantation.pdf'),
  ('Physique', 'Condensateur', 'Physique_2019_SVT-SMP_Condensateur.pdf'),
  ('Physique', 'Induction electromagnetique', 'Physique_2019_SVT-SMP_Induction.pdf'),
  ('Physique', 'Transformateur', 'Physique_2019_SVT-SMP_Transformateur.pdf'),
  ('Physique', 'Regression lineaire', 'physique-2020-SVT-regression-.pdf'),
  ('Physique', 'Regression lineaire', 'Physique_2020_SVT-SMP_Regression-Bacc-Copy.pdf'),
  ('Physique', 'Methode de la tangente', 'Physique_2020_SVT-SMP_Tangente.pdf'),
  ('Physique', 'Bobine', 'Physique_2021_SES_Bobine-Bacc-Copy.pdf'),
  ('Physique', 'Armature de condensateur', 'Physique_2021_SVT-SMP_Armature.pdf'),
  ('Physique', 'Roue de Barlow', 'Physique_2021_SVT-SMP_Barlow.pdf'),
  ('Physique', 'Big Bang', 'Physique_2022_SES_Big-bang.pdf'),
  ('Physique', 'Rayonnement cosmique', 'Physique_2022_SES_Cosmique.pdf'),
  ('Physique', 'Electromagnetisme', 'Physique_2022_SES_Electromagnetisme.pdf'),
  ('Physique', 'Englert', 'Physique_2022_SES_Englert.pdf'),
  ('Physique', 'Etoiles', 'Physique_2022_SES_Etoile.pdf'),
  ('Physique', 'Gravite', 'Physique_2022_SES_Gravite.pdf'),
  ('Physique', 'Kajita', 'Physique_2022_SES_Kajita.pdf'),
  ('Physique', 'Marconi et ondes', 'Physique_2022_SES_Marconi.pdf'),
  ('Physique', 'Effet Oncle', 'Physique_2022_SES_Oncle.pdf'),
  ('Physique', 'Perl', 'Physique_2022_SES_Perl.pdf'),
  ('Physique', 'Picard', 'Physique_2022_SES_Picard.pdf'),
  ('Physique', 'Curien', 'Physique_2022_SMP-SVT-Curien.pdf'),
  ('Physique', 'Heisenberg', 'Physique_2022_SMP-SVT-Heiseiberg.pdf'),
  ('Physique', 'Schrodinger', 'Physique_2022_SMP-SVT-Schrodinger.pdf'),
  ('Physique', 'Becquerel', 'Physique_2022_SMP-SVT_Becquerel.pdf'),
  ('Physique', 'Charpak', 'Physique_2022_SMP-SVT_Charpak-1.pdf'),
  ('Physique', 'Wineland', 'Physique_2022_SMP-SVT_Wineland.pdf'),
  ('Physique', 'GPS et relativite', 'Physique_2022_SVT-SMP_GPS.pdf'),
  ('Physique', 'Lumiere', 'Physique_2022_SVT-SMP_Lumiere.pdf'),
  ('Physique', 'Plasma', 'Physique_2022_SVT-SMP_Plasma.pdf'),
  ('Physique', 'Polymeres', 'Physique_2022_SVT-SMP_Polymeres.pdf'),
  ('Physique', 'Quanta', 'Physique_2022_SVT-SMP_Quanta.pdf')
ON CONFLICT DO NOTHING;
